
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-2
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-2
pull_requests: [{"author":{"id":"U_kgDOBtKZtg","is_bot":false,"login":"jgarcia-ucsb","name":""},"headRefName":"jg-tableOverflow","number":38,"title":"Fixed table overflow for profits table. Added a scroller when horizontal view is less than 1800px","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/38"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-update-workflows","number":37,"title":"pc - update workflows","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/37"},{"author":{"id":"MDQ6VXNlcjUxMzkzMTI3","is_bot":false,"login":"chriscerie","name":"Chris Chang"},"headRefName":"last-online","number":35,"title":"Show last online time for users","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/35"},{"author":{"id":"MDQ6VXNlcjU1NzMxNTE4","is_bot":false,"login":"camwc","name":"Cameron Cummins"},"headRefName":"cowDeath","number":34,"title":"Cow death","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/34"},{"author":{"id":"MDQ6VXNlcjUxMzkzMTI3","is_bot":false,"login":"chriscerie","name":"Chris Chang"},"headRefName":"cowherd-entity","number":32,"title":"Add CowHerd entity","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/32"},{"author":{"id":"U_kgDOBtKZtg","is_bot":false,"login":"jgarcia-ucsb","name":""},"headRefName":"jg-pr-17-25-pr3","number":28,"title":"Added Functionality to cows sold and bought through UserCommonsController","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/28"},{"author":{"id":"U_kgDOBtKZtg","is_bot":false,"login":"jgarcia-ucsb","name":""},"headRefName":"jg-pr-17-25-pr2","number":27,"title":"Added Cows Sold and Bought Variables to UserCommons entity","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/27"},{"author":{"id":"MDQ6VXNlcjIyNTMyNTU1","is_bot":false,"login":"agiduthuri","name":"Anand Giduthuri"},"headRefName":"ag-showMilkPrice","number":23,"title":"Added milk price to player's profits section","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/23"}]
