
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-2
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxMzkzMTI3","is_bot":false,"login":"chriscerie","name":"Chris Chang"},"headRefName":"cow-healthbar","number":21,"title":"Update cow health display to be a healthbar","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/21"},{"author":{"id":"MDQ6VXNlcjUxMzkzMTI3","is_bot":false,"login":"chriscerie","name":"Chris Chang"},"headRefName":"remove-effect","number":19,"title":"Remove unnecessary state and effect from HomePage","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/19"},{"author":{"id":"MDQ6VXNlcjUxMzkzMTI3","is_bot":false,"login":"chriscerie","name":"Chris Chang"},"headRefName":"readme-links","number":18,"title":"Update readme links","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/18"},{"author":{"id":"U_kgDOBtKZtg","is_bot":false,"login":"jgarcia-ucsb","name":""},"headRefName":"jg-cowsbought","number":17,"title":"Added another variable of total cows bought with functionality","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/17"},{"author":{"id":"MDQ6VXNlcjUxMzkzMTI3","is_bot":false,"login":"chriscerie","name":"Chris Chang"},"headRefName":"update-commons-card-info","number":16,"title":"Change profile commons cards to display wealth and cows and compartmentalize commons card","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/16"},{"author":{"id":"MDQ6VXNlcjM2NTczMjU5","is_bot":false,"login":"Jacob10383","name":"Jacob"},"headRefName":"JT-BuyHerd","number":13,"title":"Frontend Functionality of Buyherd","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/13"}]
