
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-2
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjczODIxMTU5","is_bot":false,"login":"RylanPow","name":""},"headRefName":"Rylan-cows-sold","number":25,"title":"Sell cows and all relevants tests.  Tested and works on LocalHost.","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/25"},{"author":{"id":"MDQ6VXNlcjUxMzkzMTI3","is_bot":false,"login":"chriscerie","name":"Chris Chang"},"headRefName":"remove-effect","number":19,"title":"Remove unnecessary state and effect from HomePage","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/19"},{"author":{"id":"U_kgDOBtKZtg","is_bot":false,"login":"jgarcia-ucsb","name":""},"headRefName":"jg-cowsbought","number":17,"title":"Added another variable of total cows bought with functionality","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/17"}]
