
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-2
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjU1NzMxNTE4","is_bot":false,"login":"camwc","name":"Cameron Cummins"},"headRefName":"cowDeath","number":34,"title":"Cow death","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/34"},{"author":{"id":"MDQ6VXNlcjUxMzkzMTI3","is_bot":false,"login":"chriscerie","name":"Chris Chang"},"headRefName":"cowherd-entity","number":32,"title":"Add CowHerd entity","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-2/pull/32"}]
